// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int times = Integer.parseInt(args[0]);
		int time1 = 0;
		int time2 = 0;
		for (int i = 0; i < times; i++) {
			if (Math.random() > 0.5) {
				time1++;
			} else {
				time2++;
		    }
		}
		if(time2 == 0) {
		   System.out.println("> 0.5: " + time1 + " times");
		   System.out.println("<= 0.5: " + time2 + " times");
		} else {
			double ratio =  (1.0 * time1) / time2;
			System.out.println("> 0.5: " + time1 + " times");
			System.out.println("<= 0.5: " + time2 + " times");
			System.out.println("ratio: " + ratio);
	    }
		
	}
}
